name: fullstack-template
services:
  app:
    container_name: app
    build:
      context: ./service
      dockerfile: Dockerfile
    depends_on:
      - db
    # host path is relative to this file, does not use build context
    # container must map with absolute path
    # volumes should only be used in development
    volumes:
      - ./service:/opt/app/service
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    # command: npm start
  db:
    container_name: db
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - '5432:5432'
    volumes: 
      - ./database/data:/var/lib/postgresql/data # volume has to be empty to init the data or else use the PGDATA var use existing data. used /data because of Dockerfile in /databases
